cloud:
  aws:
    credentials:
      access-key: AKIATKIWJ64SZUG3KO54
      secret-key: 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
    region:
      static: eu-central-1
#    stack:
#      auto: false

application:
  bucket:
    name: jdanimalsworld

spring:
  servlet:
    multipart:
      max-request-size: 1MB

server:
  port: 8080
  tomcat:
    max-swallow-size: 1MB
